USE [master]
GO

/****** Object:  Database [Hospital]    Script Date: 24.03.2020 14:25:54 ******/
CREATE DATABASE [Hospital]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hospital', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Hospital.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Hospital_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Hospital_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Hospital] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hospital].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hospital] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hospital] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hospital] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hospital] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hospital] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hospital] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hospital] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hospital] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hospital] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hospital] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hospital] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hospital] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hospital] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hospital] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hospital] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Hospital] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hospital] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hospital] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hospital] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hospital] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hospital] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Hospital] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Hospital] SET RECOVERY FULL 
GO

ALTER DATABASE [Hospital] SET  MULTI_USER 
GO

ALTER DATABASE [Hospital] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Hospital] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Hospital] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Hospital] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Hospital] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Hospital] SET QUERY_STORE = OFF
GO

USE [Hospital]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Hospital] SET  READ_WRITE 
GO

